#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: tiller
#  namespace: kube-system
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: gauravbharadwaj.bharadwaj@gmail.com
  namespace: kube-system