apiVersion: v1
kind: ConfigMap
data:
  SqlUrl: {{ .Values.configMap.sqlUrl }}
  RabbitUrl: {{ .Values.configMap.rabbitUrl }}
  FireId: {{ .Values.configMap.fireId }}
metadata:
  name: {{ .Release.Name }}
  namespace: default