apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "myapiHelm.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "myapiHelm.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "myapiHelm.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "myapiHelm.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYAPI_SQL_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: SqlUrl
            - name: MYAPI_RABBIT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: RabbitUrl
            - name: MYAPI_FIREBASE_SERVICE_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: FireId
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

