apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.post.name }}
  namespace: {{ .Values.post.namespace }}

  labels:
    app.kubernetes.io/name: postapiserv
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.post.service.port }}
    targetPort: {{ .Values.post.service.targetport }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: postapideploy

status:
  loadBalancer: {}

