apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.scrap.name }}
  namespace: {{ .Values.scrap.namespace }}

  labels:
    app.kubernetes.io/name: scrapapi
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.scrap.service.port }}
    targetPort: {{ .Values.scrap.targetport }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: scrapapi

status:
  loadBalancer: {}

